### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by jmduke** [daguar/easy-choropleths#8]
Hey!  Happened upon this after getting frustrated with the existing choropleth creation options and thought it was a great jumping off point -- are you still interested in working on this (or at least accepting PRs)?  There are a few things I'd like to fix/enhance.

**Comment by daguar** [comment]
Hey Justin! Definitely open to continuing work on it (and PRs!)

I'd stalled out a little bit due to bandwidth, but would love to know what you have in mind and see what we can do!

**Comment by jmduke** [comment]
Awesome!  Two quick/small QoL additions I was hoping for (and would be more than happy to submit them myself):
- Accepting attributes for `color` besides blue and green: I was thinking accepting an arbitrary hex (and then creating a gradient for it) would be relatively trivial.
- Defaulting unlisted states to 0 (it appears they're defaulted to -1 currently, which causes some weird rendering issues if I try and render a GDoc with just a few states.)

Curious to hear your thoughts, and have a good Monday!

**Comment by daguar** [comment]
Both sound like great improvements! Want to open an issue for each?

Also, you might want to check out ProPublica's Stateline/Landline project in case it's useful for you:
http://www.propublica.org/nerds/item/introducing-landline-and-stateline-two-tools-for-quick-vector-maps-in-your-

**Comment by jmduke** [comment]
Glad to hear it!  I'll open issues for both (and hopefully should have PRs out this evening or tomorrow).

Also, thanks for the link -- that's incredible, and I'm super tempted to write a Python wrapper around it because I am exceptionally lazy.

Closing this issue.
